const Chateaudeau = {
"type": "FeatureCollection",
"name": "Chateaudeau",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": 1, "ID": 143.0, "NOM": "Chateau d eau rue du Garde Chasse", "COMMUNE": "Les Lilas", "INSEE": 93045.0, "TYPE": "Château d'eau", "SOURCE": "ville-leslilas.fr", "COMMENTAIR": null, "DATE": "1914", "ADRESSE": "69 rue du Garde Chasse", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/tt5kVeCRnVtfZLgB6", "layer": "chateau_eau_disparu", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_disparu.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.419370995878924, 48.883778356804882 ] } },
{ "type": "Feature", "properties": { "fid": 2, "ID": 180.0, "NOM": "Chateau d eau", "COMMUNE": "Saint-Denis", "INSEE": 93066.0, "TYPE": "Château d'eau", "SOURCE": "patrimoine.seinesaintdenis.fr", "COMMENTAIR": "Present sur une carte postale ancienne. Se situait a cote de l ecole", "DATE": null, "ADRESSE": "1 boulevard Felix Faure", "PROPRIO": null, "PROTECTION": null, "pr_disp": "disparu", "phot": "https://goo.gl/maps/xwaUHDoitno5CagJA", "layer": "chateau_eau_disparu", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_disparu.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.357575679192055, 48.938793633404821 ] } },
{ "type": "Feature", "properties": { "fid": 3, "ID": 415.0, "NOM": "Château d'eau", "COMMUNE": "Pantin", "INSEE": 93055.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "196 avenue du Général Leclerc", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/YPsvL6eN7VmoSSkJ8", "layer": "chateau_eau_disparu", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_disparu.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.415292551914629, 48.902214610872036 ] } },
{ "type": "Feature", "properties": { "fid": 4, "ID": 420.0, "NOM": "Château d'eau", "COMMUNE": "Romainville", "INSEE": 93063.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "41 rue du chemin vert", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/aWSC4MgUXJRGn6GU6", "layer": "chateau_eau_disparu", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_disparu.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.448453007493937, 48.876460785224346 ] } },
{ "type": "Feature", "properties": { "fid": 5, "ID": 413.0, "NOM": "Château d'eau", "COMMUNE": "Les Lilas", "INSEE": 93045.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "6 rue du château", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/66ehQaF6V5dkzoNR6", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.421862334482845, 48.883102239351651 ] } },
{ "type": "Feature", "properties": { "fid": 6, "ID": 416.0, "NOM": "Château d'eau", "COMMUNE": "Pantin", "INSEE": 93055.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "47 chemin des vignes", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/Eo33DeuZC53v1Fcv5", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.420193124324812, 48.902313585060163 ] } },
{ "type": "Feature", "properties": { "fid": 7, "ID": 418.0, "NOM": "Château d'eau", "COMMUNE": "Noisy-le-Sec", "INSEE": 93053.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "40 rue de Paris", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/D8G6zj6YyXgKmrzK7", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.445462950226163, 48.898403026706426 ] } },
{ "type": "Feature", "properties": { "fid": 8, "ID": 419.0, "NOM": "Château d'eau", "COMMUNE": "Romainville", "INSEE": 93063.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "156 avenue de Metz", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/R4Es7hDokDeAVcGj8", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.44060821505558, 48.897402951785061 ] } },
{ "type": "Feature", "properties": { "fid": 9, "ID": 421.0, "NOM": "Château d'eau", "COMMUNE": "Romainville", "INSEE": 93063.0, "TYPE": "Château d'eau", "SOURCE": "Est Ensemble", "COMMENTAIR": null, "DATE": null, "ADRESSE": "60 route de Montreuil", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/ER5R99tqCJAAuzFz5", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.448739993259603, 48.876334885087438 ] } },
{ "type": "Feature", "properties": { "fid": 10, "ID": 839.0, "NOM": "Château d'eau", "COMMUNE": "Saint-Denis", "INSEE": 93066.0, "TYPE": "Château d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "SNCF Technicentre du Landy", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/fUb4sj3hPF9XUSAe7", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.352791440491829, 48.909350778957517 ] } },
{ "type": "Feature", "properties": { "fid": 11, "ID": 1007.0, "NOM": "Château d'eau", "COMMUNE": "Montfermeil", "INSEE": 93047.0, "TYPE": "Château d'eau", "SOURCE": "Ville de Montfermeil", "COMMENTAIR": null, "DATE": null, "ADRESSE": "7 avenue des Lilas", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/pF34kgtPKmHvUVfT7", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.557177288417754, 48.898790983685075 ] } },
{ "type": "Feature", "properties": { "fid": 12, "ID": 1059.0, "NOM": "Château d'eau", "COMMUNE": "Villepinte", "INSEE": 93078.0, "TYPE": "Château d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "Parc du Sausset", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/QQEH5Ex7sq31ybFJ8", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.505868391714359, 48.967949987896759 ] } },
{ "type": "Feature", "properties": { "fid": 13, "ID": 1060.0, "NOM": "Château d'eau", "COMMUNE": "Villepinte", "INSEE": 93078.0, "TYPE": "Château d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "Parc du Sausset", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/QQEH5Ex7sq31ybFJ8", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.506102358226537, 48.968196425677363 ] } },
{ "type": "Feature", "properties": { "fid": 14, "ID": 1061.0, "NOM": "Château d'eau", "COMMUNE": "Villepinte", "INSEE": 93078.0, "TYPE": "Château d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "Parc du Sausset", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/QQEH5Ex7sq31ybFJ8", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.506585328465033, 48.968212243167052 ] } },
{ "type": "Feature", "properties": { "fid": 15, "ID": 1080.0, "NOM": "Château d'eau", "COMMUNE": "Villepinte", "INSEE": 93078.0, "TYPE": "Château d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "173 boulevard Robert Ballanger", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/zdgHmbMoShtccYxt9", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.538465207867057, 48.955856618370689 ] } },
{ "type": "Feature", "properties": { "fid": 16, "ID": 1513.0, "NOM": "Château d'eau", "COMMUNE": "Le Blanc-Mesnil", "INSEE": 93007.0, "TYPE": "Château d'eau", "SOURCE": "APUR", "COMMENTAIR": null, "DATE": null, "ADRESSE": "Allée des Droits de l'Homme", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/kuqMLN82T7B8CVkMA", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.460992438826031, 48.947438004534753 ] } },
{ "type": "Feature", "properties": { "fid": 17, "ID": 1514.0, "NOM": "Château d'eau", "COMMUNE": "Le Blanc-Mesnil", "INSEE": 93007.0, "TYPE": "Château d'eau", "SOURCE": "APUR", "COMMENTAIR": null, "DATE": null, "ADRESSE": "7 avenue de la Division Leclerc", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://goo.gl/maps/TyjBQeoc5FgreFSB6", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.465390086371313, 48.943697238346402 ] } },
{ "type": "Feature", "properties": { "fid": 18, "ID": 1515.0, "NOM": "Château d'eau", "COMMUNE": "La Courneuve", "INSEE": 93027.0, "TYPE": "Château d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "85 D901", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent(sur image satellite)", "phot": "https://goo.gl/maps/g3z4T9HdKcy3XoQ58", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.384624110551679, 48.925572368950476 ] } },
{ "type": "Feature", "properties": { "fid": 19, "ID": 1516.0, "NOM": "Château d'eau", "COMMUNE": "Clichy-sous-Bois", "INSEE": 93014.0, "TYPE": "2 châteaux d'eau", "SOURCE": "Open Street Map", "COMMENTAIR": null, "DATE": null, "ADRESSE": "137 allée de Montfermeil", "PROPRIO": null, "PROTECTION": null, "pr_disp": "présent", "phot": "https://www.google.com/maps/@48.897367,2.5328516,3a,90y,325.93h,110.27t/data=!3m9!1e1!3m7!1sqf3nQHvx-iY8WZjaPetpIQ!2e0!7i16384!8i8192!9m2!1b1!2i22?coh=205409&entry=ttu", "layer": "chateau_eau_present", "path": "C:/Users/helve/Downloads/SSD/KS/2023_StageCarto_KhadidiatouSy/nouvelle_couche_SIG/chateau_eau_present.shp" }, "geometry": { "type": "Point", "coordinates": [ 2.532657777513772, 48.897583479125018 ] } }
]
}
